# Generated by Django 6.0.3 on 2026-03-14 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmShield', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FarmShield.reading'),
        ),
    ]
